version: '3.8'
services:
  jupyter-ros2:
    image: intel4coro/jupyter-ros2:humble-py3.10
    build:
      context: ./
#      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports: 
      - 8888:8888
      - 11311:11311
    privileged: true
    #user: root
    user: jovyan
    environment:
      GRANT_SUDO: "yes"
      NB_GID: 100
      NB_USER: "jovyan"
      CHOWN_HOME: "yes" 
    working_dir: /home/jovyan
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    entrypoint: ["/home/jovyan/work/entrypoint.sh"]
    volumes:
      - ./:/home/jovyan/work
      - /dev:/dev
      - /dev/snd:/dev/snd
      - /sys:/sys
      - /tmp/esp32-proxy.socket:/tmp/esp32-proxy.socket
    devices:
      - "/dev/snd:/dev/snd"
    #   - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # environment:
    #   - DISPLAY
    #   - NVIDIA_DRIVER_CAPABILITIES=all
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
